global:
  defaultStorageClass: "nfs-client"
 
drupalProfile: standard
drupalUsername: andrei
drupalPassword: "drupal1234"
drupalEmail: taa421992@gmail.com

persistence:
  enabled: true
  storageClass: "nfs-client"
  accessModes:
    - ReadWriteMany
  size: 1Gi
resourcesPreset: "micro"

service:
  type: NodePort
  
ingress:
  enabled: true
  ingressClassName: "nginx"
  hostname: drupal.k8s-19.sa
 
mariadb:
  enabled: true
  auth:
    rootPassword: "drupal-1234"
    database: bitnami_drupal
    username: bn_drupal
    password: "bn_drupal-12345"
  primary:
    persistence:
      enabled: true
      storageClass: "nfs-client"
      accessModes:
        - ReadWriteMany
      size: 1Gi
