---
apiVersion: v1
kind: PresistentVolumeClaim
metadata:
  name: drupal-pv-claim
  labels: 
   app: drupal
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-client
  resourses:
    requests:
      storage: 1Gi
---
global:
  storageClass: nfs-client
service:
  type: NodePort
  nodePort: 30001
  drupalUsername: "admin"
  drupalPassword: "1234"       
  drupalEmail: admin@example.com
mariadb:
  primary:
    persistence:
      enabled: true
      storageClass: nfs-client
